; config file for encoding parameter

[app]
; encoder_stream
; encoder_dump
; decoder
; rtsp
mode = rtsp

[network]
ip = 192.168.13.53
netmask = 255.255.255.0
gateway = 192.168.13.254

[encoder]
# Video SIZE
; default (3840 x 2160)
; FHD     (1920 x 1080)
width    = 1920
height   = 1080

# encoding mode
# cbr
# vbr
rc_mode     = cbr

# CODEC type
# h264
# h265
codec    = h265

# framerate
fps      = 30

# bitrate (bps)
bitrate  = 2300000

# GOP (Group of Pictures)
gop      = 30

# QP ( Quantization Parameter )
qp_start = 35
qp_min   = 25
qp_max   = 40

[decoder]
# decoder output type
; h264
; h265
output_codec_type = h265

# decoder framerate (fps)
fps      = 30

